// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package logtrace

import (
	"errors"
	"fmt"
)

const (
	// InvitationStatusPending is a InvitationStatus of type pending.
	InvitationStatusPending InvitationStatus = "pending"
	// InvitationStatusAccepted is a InvitationStatus of type accepted.
	InvitationStatusAccepted InvitationStatus = "accepted"
	// InvitationStatusDeclined is a InvitationStatus of type declined.
	InvitationStatusDeclined InvitationStatus = "declined"
	// InvitationStatusExpired is a InvitationStatus of type expired.
	InvitationStatusExpired InvitationStatus = "expired"
	// InvitationStatusRevoked is a InvitationStatus of type revoked.
	InvitationStatusRevoked InvitationStatus = "revoked"
)

var ErrInvalidInvitationStatus = errors.New("not a valid InvitationStatus")

// String implements the Stringer interface.
func (x InvitationStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x InvitationStatus) IsValid() bool {
	_, err := ParseInvitationStatus(string(x))
	return err == nil
}

var _InvitationStatusValue = map[string]InvitationStatus{
	"pending":  InvitationStatusPending,
	"accepted": InvitationStatusAccepted,
	"declined": InvitationStatusDeclined,
	"expired":  InvitationStatusExpired,
	"revoked":  InvitationStatusRevoked,
}

// ParseInvitationStatus attempts to convert a string to a InvitationStatus.
func ParseInvitationStatus(name string) (InvitationStatus, error) {
	if x, ok := _InvitationStatusValue[name]; ok {
		return x, nil
	}
	return InvitationStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidInvitationStatus)
}
