// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package logtrace

import (
	"errors"
	"fmt"
)

const (
	// SessionStatusSuccesful is a SessionStatus of type succesful.
	SessionStatusSuccesful SessionStatus = "succesful"
	// SessionStatusFailed is a SessionStatus of type failed.
	SessionStatusFailed SessionStatus = "failed"
	// SessionStatusExpired is a SessionStatus of type expired.
	SessionStatusExpired SessionStatus = "expired"
	// SessionStatusActive is a SessionStatus of type active.
	SessionStatusActive SessionStatus = "active"
)

var ErrInvalidSessionStatus = errors.New("not a valid SessionStatus")

// String implements the Stringer interface.
func (x SessionStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SessionStatus) IsValid() bool {
	_, err := ParseSessionStatus(string(x))
	return err == nil
}

var _SessionStatusValue = map[string]SessionStatus{
	"succesful": SessionStatusSuccesful,
	"failed":    SessionStatusFailed,
	"expired":   SessionStatusExpired,
	"active":    SessionStatusActive,
}

// ParseSessionStatus attempts to convert a string to a SessionStatus.
func ParseSessionStatus(name string) (SessionStatus, error) {
	if x, ok := _SessionStatusValue[name]; ok {
		return x, nil
	}
	return SessionStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidSessionStatus)
}
