version: "3"

tasks:
  tidy:
    desc: Fix the dependencies
    cmds:
      - go mod tidy

  lint:
    desc: Lint all the Go files using golangci-lint
    cmds:
      - golangci-lint run ./...

  generate:all:
    desc: Build all
    cmds:
      - go generate ./...
      - cd ../app && npm run swagger && cd -

  migrate:create:
    desc: Create a new migration file
    vars:
      NAME: "{{.CLI_ARGS}}"
    cmds:
      - migrate create -ext sql -dir ./internal/datastore/postgres/migrations {{.NAME}}

  env:
    desc: Export environment variables from Infisical
    cmds:
      - infisical export --env=dev > .env

  migrate:down:one:
    desc: Rollback the last database migration
    cmds:
      - migrate -path ./internal/datastore/postgres/migrations/ -database "postgres://postgres:password@localhost:5432/logtrace?sslmode=disable" down 1

  migrate:
    desc: Apply all up database migrations
    cmds:
      - migrate -path ./internal/datastore/postgres/migrations/ -database "postgres://postgres:password@localhost:5432/logtrace?sslmode=disable" up

  run:http:
    desc: Run the HTTP server
    cmds:
      - air
  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  test-all:
    desc: Run all tests including integration tests
    cmds:
      - go test -v -tags integration ./...
