// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package logbase

import (
	"errors"
	"fmt"
)

const (
	// UserStatusActive is a UserStatus of type active.
	UserStatusActive UserStatus = "active"
	// UserStatusInactive is a UserStatus of type inactive.
	UserStatusInactive UserStatus = "inactive"
	// UserStatusPending is a UserStatus of type pending.
	UserStatusPending UserStatus = "pending"
)

var ErrInvalidUserStatus = errors.New("not a valid UserStatus")

// String implements the Stringer interface.
func (x UserStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UserStatus) IsValid() bool {
	_, err := ParseUserStatus(string(x))
	return err == nil
}

var _UserStatusValue = map[string]UserStatus{
	"active":   UserStatusActive,
	"inactive": UserStatusInactive,
	"pending":  UserStatusPending,
}

// ParseUserStatus attempts to convert a string to a UserStatus.
func ParseUserStatus(name string) (UserStatus, error) {
	if x, ok := _UserStatusValue[name]; ok {
		return x, nil
	}
	return UserStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidUserStatus)
}
