// Code generated by MockGen. DO NOT EDIT.
// Source: google_auth.go
//
// Generated by this command:
//
//	mockgen -source=google_auth.go -destination=mocks/google_auth.go -package=googleauth_mocks
//

// Package googleauth_mocks is a generated GoMock package.
package googleauth_mocks

import (
	context "context"
	reflect "reflect"

	googleauth "gitlab.com/logbase/logbase/internal/pkg/googleauth"
	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockGoogleAuthProvider is a mock of GoogleAuthProvider interface.
type MockGoogleAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleAuthProviderMockRecorder
	isgomock struct{}
}

// MockGoogleAuthProviderMockRecorder is the mock recorder for MockGoogleAuthProvider.
type MockGoogleAuthProviderMockRecorder struct {
	mock *MockGoogleAuthProvider
}

// NewMockGoogleAuthProvider creates a new mock instance.
func NewMockGoogleAuthProvider(ctrl *gomock.Controller) *MockGoogleAuthProvider {
	mock := &MockGoogleAuthProvider{ctrl: ctrl}
	mock.recorder = &MockGoogleAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleAuthProvider) EXPECT() *MockGoogleAuthProviderMockRecorder {
	return m.recorder
}

// User mocks base method.
func (m *MockGoogleAuthProvider) User(arg0 context.Context, arg1 *oauth2.Token) (googleauth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", arg0, arg1)
	ret0, _ := ret[0].(googleauth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockGoogleAuthProviderMockRecorder) User(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockGoogleAuthProvider)(nil).User), arg0, arg1)
}

// Validate mocks base method.
func (m *MockGoogleAuthProvider) Validate(arg0 context.Context, arg1 googleauth.ValidateOptions) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0, arg1)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockGoogleAuthProviderMockRecorder) Validate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGoogleAuthProvider)(nil).Validate), arg0, arg1)
}
