package seed

import (
	"time"

	"gitlab.com/logtrace/logtrace"
)

// EventSeedData returns 10 event records with unique action names.
func EventSeedData() []logtrace.Event {
	now := time.Now().UTC()
	return []logtrace.Event{
		{
			Name: "user.login", Type: "authentication",
			Username: "alice morgan", UserID: "usr_001",
			Metadata:  logtrace.Metadata{"browser": "Chrome", "os": "Windows 10"},
			CreatedAt: now,
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/auth/login",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.1.10",
				ClientUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/114.0",
				GeoIPLocation:   "New York, US",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
		},
		{
			Name: "user.logout", Type: "authentication",
			Username: "bob hartley", UserID: "usr_002",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/auth/logout",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.1.11",
				OperatingSystem: "macOS Ventura",
				ClientUserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4) Safari/16.0",
				GeoIPLocation:   "San Francisco, US",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Metadata:  logtrace.Metadata{"browser": "Safari", "os": "macOS"},
			CreatedAt: now,
		},
		{
			Name: "payment.initiated", Type: "transaction",
			Username: "carol nguyen", UserID: "usr_003",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/payments",
				HTTPStatusCode:  201,
				IPAddress:       "172.16.0.20",
				ClientUserAgent: "axios/1.4.0",
				GeoIPLocation:   "London, GB",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Metadata:  logtrace.Metadata{"amount": "99.99", "currency": "USD"},
			CreatedAt: now,
		},
		{
			Name: "profile.updated", Type: "account",
			Username: "david okafor", UserID: "usr_004",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "PATCH", HTTPEndpoint: "/users/profile",
				HTTPStatusCode:  200,
				IPAddress:       "203.0.113.45",
				ClientUserAgent: "okhttp/4.9.3",
				GeoIPLocation:   "Lagos, NG",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Metadata:  logtrace.Metadata{"fields_changed": "email,phone"},
			CreatedAt: now,
		},
		{
			Name: "document.uploaded", Type: "file",
			Username: "emily svensson", UserID: "usr_005",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/documents/upload",
				HTTPStatusCode:  201,
				IPAddress:       "198.51.100.33",
				ClientUserAgent: "Mozilla/5.0 (X11; Linux x86_64)",
				GeoIPLocation:   "Stockholm, SE",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Metadata:  logtrace.Metadata{"file_type": "pdf", "size_kb": "1024"},
			CreatedAt: now,
		},
		{
			Name: "api_key.created", Type: "developer",
			Username: "frank delacroix", UserID: "usr_006",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/developers/keys",
				HTTPStatusCode:  201,
				IPAddress:       "192.0.2.88",
				ClientUserAgent: "PostmanRuntime/7.32.0",
				GeoIPLocation:   "Paris, FR",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Metadata:  logtrace.Metadata{"key_prefix": "ltk_live"},
			CreatedAt: now,
		},
		{
			Name: "password.reset", Type: "security",
			Username: "grace kimani", UserID: "usr_007",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/auth/password/reset",
				HTTPStatusCode:  200,
				IPAddress:       "100.64.0.12",
				ClientUserAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0)",
				GeoIPLocation:   "Nairobi, KE",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Metadata:  logtrace.Metadata{"method": "email_link"},
			CreatedAt: now,
		},
		{
			Name: "report.exported", Type: "data",
			Username: "henry walker", UserID: "usr_008",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/reports/export",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.10.50",
				ClientUserAgent: "python-requests/2.31.0",
				GeoIPLocation:   "Sydney, AU",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Metadata:  logtrace.Metadata{"format": "csv", "rows": "5000"},
			CreatedAt: now,
		},
		{
			Name: "webhook.triggered", Type: "integration",
			Username: "isabella costa", UserID: "usr_009",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/webhooks/trigger",
				HTTPStatusCode:  200,
				IPAddress:       "203.0.113.99",
				ClientUserAgent: "node-fetch/3.3.0",
				GeoIPLocation:   "São Paulo, BR",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Metadata:  logtrace.Metadata{"event_type": "payment.success"},
			CreatedAt: now,
		},
		{
			Name: "organization.created", Type: "admin",
			Username: "james otieno", UserID: "usr_010",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/organizations",
				HTTPStatusCode:  201,
				IPAddress:       "10.10.0.1",
				ClientUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
				GeoIPLocation:   "Kampala, UG",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Metadata:  logtrace.Metadata{"plan": "starter"},
			CreatedAt: now,
		},
	}
}

// SessionSeedData returns 10 session records with unique user names.
func SessionSeedData() []logtrace.Session {
	now := time.Now().UTC()
	return []logtrace.Session{
		{
			UserID: "usr_001", UserName: "alice morgan",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:       now,
				HTTPMethod:      "GET",
				HTTPEndpoint:    "/dashboard",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.1.10",
				ClientUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/114.0",
				GeoIPLocation:   "New York, US",
				OperatingSystem: "Windows 10",
			},
			Status: "active", Token: "tok_alice_001",
			LoginAt:  now.Add(-2 * time.Hour),
			Metadata: logtrace.Metadata{"mfa": "true"},
		},
		{
			UserID: "usr_002", UserName: "bob hartley",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/organizations",
				HTTPStatusCode:  201,
				IPAddress:       "10.10.0.1",
				ClientUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
				GeoIPLocation:   "Kampala, UG",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Status: "active", Token: "tok_bob_002",
			LoginAt:  now.Add(-45 * time.Minute),
			Metadata: logtrace.Metadata{"mfa": "false"},
		},
		{
			UserID: "usr_003", UserName: "carol nguyen",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/profile",
				HTTPStatusCode:  200,
				IPAddress:       "172.16.0.20",
				ClientUserAgent: "Firefox/115.0",
				GeoIPLocation:   "London, GB",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "succesful", Token: "tok_carol_003",
			LoginAt:  now.Add(-5 * time.Hour),
			LogoutAt: now.Add(-4 * time.Hour),
			Metadata: logtrace.Metadata{"mfa": "true"},
		},
		{
			UserID: "usr_004", UserName: "david okafor",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/settings",
				HTTPStatusCode:  200,
				IPAddress:       "203.0.113.45",
				ClientUserAgent: "okhttp/4.9.1",
				GeoIPLocation:   "Lagos, NG",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "expired", Token: "tok_david_004",
			LoginAt:  now.Add(-26 * time.Hour),
			LogoutAt: now.Add(-25 * time.Hour),
			Metadata: logtrace.Metadata{"mfa": "false"},
		},
		{
			UserID: "usr_005", UserName: "emily svensson",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/profile",
				HTTPStatusCode:  200,
				IPAddress:       "198.51.100.33",
				ClientUserAgent: "Chrome/114.0",
				GeoIPLocation:   "Stockholm, SE",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "active", Token: "tok_emily_005",
			LoginAt:  now.Add(-30 * time.Minute),
			Metadata: logtrace.Metadata{"mfa": "true"},
		},
		{
			UserID: "usr_006", UserName: "frank delacroix",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/profile",
				HTTPStatusCode:  200,
				IPAddress:       "192.0.2.88",
				ClientUserAgent: "Postman",
				GeoIPLocation:   "Paris, FR",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "succesful", Token: "tok_frank_006",
			LoginAt:  now.Add(-3 * time.Hour),
			LogoutAt: now.Add(-2*time.Hour - 30*time.Minute),
			Metadata: logtrace.Metadata{"mfa": "true"},
		},
		{
			UserID: "usr_007", UserName: "grace kimani",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/profile",
				HTTPStatusCode:  200,
				IPAddress:       "100.64.0.12",
				ClientUserAgent: "Mobile Safari",
				GeoIPLocation:   "Nairobi, KE",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "active", Token: "tok_grace_007",
			LoginAt:  now.Add(-10 * time.Minute),
			Metadata: logtrace.Metadata{"mfa": "false"},
		},
		{
			UserID: "usr_008", UserName: "henry walker",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "POST", HTTPEndpoint: "/login",
				HTTPStatusCode:  401,
				IPAddress:       "192.168.10.50",
				ClientUserAgent: "python-requests / Linux",
				GeoIPLocation:   "Sydney, AU",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Status: "failed", Token: "tok_henry_008",
			LoginAt:  now.Add(-1 * time.Hour),
			Metadata: logtrace.Metadata{"reason": "invalid_credentials"},
		},
		{
			UserID: "usr_009", UserName: "isabella costa",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/profile",
				HTTPStatusCode:  200,
				IPAddress:       "203.0.113.99",
				ClientUserAgent: "node-fetch / Node.js 18",
				GeoIPLocation:   "São Paulo, BR",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "active", Token: "tok_isabella_009",
			LoginAt:  now.Add(-15 * time.Minute),
			Metadata: logtrace.Metadata{"mfa": "true"},
		},
		{
			UserID: "usr_010", UserName: "james otieno",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  time.Now().UTC(),
				HTTPMethod: "GET", HTTPEndpoint: "/profile",
				HTTPStatusCode:  200,
				IPAddress:       "10.10.0.1",
				ClientUserAgent: "Chrome 114 / Windows 11",
				GeoIPLocation:   "Kampala, UG",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "100ms",
			},
			Status: "active", Token: "tok_james_010",
			LoginAt:  now.Add(-5 * time.Minute),
			Metadata: logtrace.Metadata{"mfa": "false"},
		},
	}
}

// AuditLogSeedData returns 10 audit log records with unique actions.
func AuditLogSeedData() []logtrace.AuditLog {
	now := time.Now().UTC()
	return []logtrace.AuditLog{
		{
			Name: "user.created", UserID: "usr_001", UserName: "alice morgan",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-2 * time.Hour),
				HTTPMethod: "POST", HTTPEndpoint: "/users",
				HTTPStatusCode:  201,
				IPAddress:       "192.168.1.10",
				ClientUserAgent: "Chrome 114",
				GeoIPLocation:   "New York, US",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "200ms",
			},
			Metadata:  logtrace.Metadata{"email": "alice.morgan@example.com"},
			Timestamp: now.Add(-2 * time.Hour),
		},
		{
			Name: "user.role_changed", UserID: "usr_002", UserName: "bob hartley",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-90 * time.Minute),
				HTTPMethod: "PATCH", HTTPEndpoint: "/users/role",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.1.20",
				ClientUserAgent: "Safari 16",
				GeoIPLocation:   "San Francisco, US",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Metadata:  logtrace.Metadata{"old_role": "member", "new_role": "admin"},
			Timestamp: now.Add(-90 * time.Minute),
		},
		{
			Name: "api_key.revoked", UserID: "usr_003", UserName: "carol nguyen",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-80 * time.Minute),
				HTTPMethod: "DELETE", HTTPEndpoint: "/api-keys",
				HTTPStatusCode:  200,
				IPAddress:       "172.16.0.20",
				ClientUserAgent: "Firefox 115",
				GeoIPLocation:   "London, GB",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "120ms",
			},
			Metadata:  logtrace.Metadata{"key_prefix": "ltk_test"},
			Timestamp: now.Add(-80 * time.Minute),
		},
		{
			Name: "billing.subscription_upgraded", UserID: "usr_004", UserName: "david okafor",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-70 * time.Minute),
				HTTPMethod: "PUT", HTTPEndpoint: "/billing/subscription",
				HTTPStatusCode:  200,
				IPAddress:       "203.0.113.45",
				ClientUserAgent: "okhttp",
				GeoIPLocation:   "Tokyo, JP",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "180ms",
			},
			Metadata:  logtrace.Metadata{"from_plan": "starter", "to_plan": "growth"},
			Timestamp: now.Add(-70 * time.Minute),
		},
		{
			Name: "organization.settings_updated", UserID: "usr_005", UserName: "emily svensson",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-60 * time.Minute),
				HTTPMethod: "PATCH", HTTPEndpoint: "/organization/settings",
				HTTPStatusCode:  200,
				IPAddress:       "198.51.100.33",
				ClientUserAgent: "Chrome 114",
				GeoIPLocation:   "Stockholm, SE",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "160ms",
			},
			Metadata:  logtrace.Metadata{"fields": "name,timezone"},
			Timestamp: now.Add(-60 * time.Minute),
		},
		{
			Name: "invitation.sent", UserID: "usr_006", UserName: "frank delacroix",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-50 * time.Minute),
				HTTPMethod: "POST", HTTPEndpoint: "/invitations",
				HTTPStatusCode:  201,
				IPAddress:       "192.0.2.88",
				ClientUserAgent: "Postman",
				GeoIPLocation:   "Berlin, DE",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "220ms",
			},
			Metadata:  logtrace.Metadata{"invited_email": "new.member@example.com"},
			Timestamp: now.Add(-50 * time.Minute),
		},
		{
			Name: "two_factor.enabled", UserID: "usr_007", UserName: "grace kimani",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-40 * time.Minute),
				HTTPMethod: "POST", HTTPEndpoint: "/settings/2fa",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.1.20",
				ClientUserAgent: "Safari 16",
				GeoIPLocation:   "San Francisco, US",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "150ms",
			},
			Metadata:  logtrace.Metadata{"method": "totp"},
			Timestamp: now.Add(-40 * time.Minute),
		},
		{
			Name: "data.export_requested", UserID: "usr_008", UserName: "henry walker",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-30 * time.Minute),
				HTTPMethod: "POST", HTTPEndpoint: "/data/export",
				HTTPStatusCode:  202,
				IPAddress:       "192.168.1.25",
				ClientUserAgent: "python-requests",
				GeoIPLocation:   "New York, US",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "200ms",
			},
			Metadata:  logtrace.Metadata{"resource": "audit_logs", "format": "json"},
			Timestamp: now.Add(-30 * time.Minute),
		},
		{
			Name: "webhook.deleted", UserID: "usr_009", UserName: "isabella costa",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-20 * time.Minute),
				HTTPMethod: "DELETE", HTTPEndpoint: "/webhooks",
				HTTPStatusCode:  200,
				IPAddress:       "192.168.1.30",
				ClientUserAgent: "node-fetch",
				GeoIPLocation:   "London, GB",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "140ms",
			},
			Metadata:  logtrace.Metadata{"webhook_url": "https://hooks.example.com/old"},
			Timestamp: now.Add(-20 * time.Minute),
		},
		{
			Name: "session.force_logout", UserID: "usr_010", UserName: "james otieno",
			RequestDetails: logtrace.RequestDetails{
				Timestamp:  now.Add(-10 * time.Minute),
				HTTPMethod: "POST", HTTPEndpoint: "/session/force-logout",
				HTTPStatusCode:  200,
				IPAddress:       "10.10.0.1",
				ClientUserAgent: "Chrome 114",
				GeoIPLocation:   "Windows 11",
				RequestHeaders:  map[string]string{"Content-Type": "application/json"},
				RequestDuration: "120ms",
			},
			Metadata:  logtrace.Metadata{"reason": "suspicious_activity"},
			Timestamp: now.Add(-10 * time.Minute),
		},
	}
}
