// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package queue

import (
	"errors"
	"fmt"
)

const (
	// QueueTopicBillingTrialEnding is a QueueTopic of type billing_trial_ending.
	QueueTopicBillingTrialEnding QueueTopic = "billing_trial_ending"
	// QueueTopicBillingCreateCustomer is a QueueTopic of type billing_create_customer.
	QueueTopicBillingCreateCustomer QueueTopic = "billing_create_customer"
	// QueueTopicInviteTeamMember is a QueueTopic of type invite_team_member.
	QueueTopicInviteTeamMember QueueTopic = "invite_team_member"
	// QueueTopicSubscriptionExpired is a QueueTopic of type subscription_expired.
	QueueTopicSubscriptionExpired QueueTopic = "subscription_expired"
	// QueueTopicVerifyEmail is a QueueTopic of type verify_email.
	QueueTopicVerifyEmail QueueTopic = "verify_email"
	// QueueTopicSaveEvent is a QueueTopic of type save_event.
	QueueTopicSaveEvent QueueTopic = "save_event"
	// QueueTopicSaveAuditLog is a QueueTopic of type save_audit_log.
	QueueTopicSaveAuditLog QueueTopic = "save_audit_log"
	// QueueTopicSaveSession is a QueueTopic of type save_session.
	QueueTopicSaveSession QueueTopic = "save_session"
	// QueueTopicAlert is a QueueTopic of type alert.
	QueueTopicAlert QueueTopic = "alert"
	// QueueTopicResetPassword is a QueueTopic of type reset_password.
	QueueTopicResetPassword QueueTopic = "reset_password"
	// QueueTopicResetPasswordSuccess is a QueueTopic of type reset_password_success.
	QueueTopicResetPasswordSuccess QueueTopic = "reset_password_success"
)

var ErrInvalidQueueTopic = errors.New("not a valid QueueTopic")

// String implements the Stringer interface.
func (x QueueTopic) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x QueueTopic) IsValid() bool {
	_, err := ParseQueueTopic(string(x))
	return err == nil
}

var _QueueTopicValue = map[string]QueueTopic{
	"billing_trial_ending":    QueueTopicBillingTrialEnding,
	"billing_create_customer": QueueTopicBillingCreateCustomer,
	"invite_team_member":      QueueTopicInviteTeamMember,
	"subscription_expired":    QueueTopicSubscriptionExpired,
	"verify_email":            QueueTopicVerifyEmail,
	"save_event":              QueueTopicSaveEvent,
	"save_audit_log":          QueueTopicSaveAuditLog,
	"save_session":            QueueTopicSaveSession,
	"alert":                   QueueTopicAlert,
	"reset_password":          QueueTopicResetPassword,
	"reset_password_success":  QueueTopicResetPasswordSuccess,
}

// ParseQueueTopic attempts to convert a string to a QueueTopic.
func ParseQueueTopic(name string) (QueueTopic, error) {
	if x, ok := _QueueTopicValue[name]; ok {
		return x, nil
	}
	return QueueTopic(""), fmt.Errorf("%s is %w", name, ErrInvalidQueueTopic)
}
