// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -source=event.go -destination=mocks/event.go -package=logtrace_mocks
//

// Package logtrace_mocks is a generated GoMock package.
package logtrace_mocks

import (
	context "context"
	reflect "reflect"

	logtrace "gitlab.com/logtrace/logtrace"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventRepository) Create(arg0 context.Context, arg1 *logtrace.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepository)(nil).Create), arg0, arg1)
}

// List mocks base method.
func (m *MockEventRepository) List(arg0 context.Context, arg1 logtrace.ListEventOptions) (*logtrace.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*logtrace.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventRepositoryMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventRepository)(nil).List), arg0, arg1)
}

// ListAll mocks base method.
func (m *MockEventRepository) ListAll(arg0 context.Context, arg1 *logtrace.ListEventOptions) ([]*logtrace.Event, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", arg0, arg1)
	ret0, _ := ret[0].([]*logtrace.Event)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAll indicates an expected call of ListAll.
func (mr *MockEventRepositoryMockRecorder) ListAll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockEventRepository)(nil).ListAll), arg0, arg1)
}

// Metrics mocks base method.
func (m *MockEventRepository) Metrics(arg0 context.Context, arg1 *logtrace.ListEventOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metrics", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metrics indicates an expected call of Metrics.
func (mr *MockEventRepositoryMockRecorder) Metrics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metrics", reflect.TypeOf((*MockEventRepository)(nil).Metrics), arg0, arg1)
}

// TopActorMetrics mocks base method.
func (m *MockEventRepository) TopActorMetrics(arg0 context.Context, arg1 *logtrace.ListEventOptions) ([]*logtrace.TopActorMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopActorMetrics", arg0, arg1)
	ret0, _ := ret[0].([]*logtrace.TopActorMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopActorMetrics indicates an expected call of TopActorMetrics.
func (mr *MockEventRepositoryMockRecorder) TopActorMetrics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopActorMetrics", reflect.TypeOf((*MockEventRepository)(nil).TopActorMetrics), arg0, arg1)
}
