// Code generated by MockGen. DO NOT EDIT.
// Source: organization_user.go
//
// Generated by this command:
//
//	mockgen -source=organization_user.go -destination=mocks/organization_user.go -package=logtrace_mocks
//

// Package logtrace_mocks is a generated GoMock package.
package logtrace_mocks

import (
	context "context"
	reflect "reflect"

	logtrace "gitlab.com/logtrace/logtrace"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationUserRepository is a mock of OrganizationUserRepository interface.
type MockOrganizationUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationUserRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationUserRepositoryMockRecorder is the mock recorder for MockOrganizationUserRepository.
type MockOrganizationUserRepositoryMockRecorder struct {
	mock *MockOrganizationUserRepository
}

// NewMockOrganizationUserRepository creates a new mock instance.
func NewMockOrganizationUserRepository(ctrl *gomock.Controller) *MockOrganizationUserRepository {
	mock := &MockOrganizationUserRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationUserRepository) EXPECT() *MockOrganizationUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationUserRepository) Create(arg0 context.Context, arg1 *logtrace.OrganizationUser) (*logtrace.OrganizationUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*logtrace.OrganizationUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationUserRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationUserRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockOrganizationUserRepository) Find(arg0 context.Context, arg1 *logtrace.FindOrganizationUserOptions) (*logtrace.OrganizationUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*logtrace.OrganizationUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockOrganizationUserRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockOrganizationUserRepository)(nil).Find), arg0, arg1)
}

// List mocks base method.
func (m *MockOrganizationUserRepository) List(arg0 context.Context, arg1 *logtrace.ListOrganizationUserOptions) ([]*logtrace.OrganizationUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*logtrace.OrganizationUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOrganizationUserRepositoryMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrganizationUserRepository)(nil).List), arg0, arg1)
}
