// Code generated by MockGen. DO NOT EDIT.
// Source: password.go
//
// Generated by this command:
//
//	mockgen -source=password.go -destination=mocks/password.go -package=logtrace_mocks
//

// Package logtrace_mocks is a generated GoMock package.
package logtrace_mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	logtrace "gitlab.com/logtrace/logtrace"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordRepository is a mock of PasswordRepository interface.
type MockPasswordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordRepositoryMockRecorder is the mock recorder for MockPasswordRepository.
type MockPasswordRepositoryMockRecorder struct {
	mock *MockPasswordRepository
}

// NewMockPasswordRepository creates a new mock instance.
func NewMockPasswordRepository(ctrl *gomock.Controller) *MockPasswordRepository {
	mock := &MockPasswordRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordRepository) EXPECT() *MockPasswordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordRepository) Create(arg0 context.Context, arg1 *logtrace.Password) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordRepository)(nil).Create), arg0, arg1)
}

// List mocks base method.
func (m *MockPasswordRepository) List(arg0 context.Context, arg1 uuid.UUID) (*logtrace.Password, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*logtrace.Password)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPasswordRepositoryMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPasswordRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockPasswordRepository) Update(arg0 context.Context, arg1 *logtrace.Password) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPasswordRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPasswordRepository)(nil).Update), arg0, arg1)
}
