// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go
//
// Generated by this command:
//
//	mockgen -source=jwt.go -destination=mocks/token.go -package=logtrace_mocks
//

// Package logtrace_mocks is a generated GoMock package.
package logtrace_mocks

import (
	reflect "reflect"

	jwttoken "gitlab.com/logtrace/logtrace/internal/pkg/jwttoken"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTokenManager is a mock of JWTokenManager interface.
type MockJWTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockJWTokenManagerMockRecorder
	isgomock struct{}
}

// MockJWTokenManagerMockRecorder is the mock recorder for MockJWTokenManager.
type MockJWTokenManagerMockRecorder struct {
	mock *MockJWTokenManager
}

// NewMockJWTokenManager creates a new mock instance.
func NewMockJWTokenManager(ctrl *gomock.Controller) *MockJWTokenManager {
	mock := &MockJWTokenManager{ctrl: ctrl}
	mock.recorder = &MockJWTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTokenManager) EXPECT() *MockJWTokenManagerMockRecorder {
	return m.recorder
}

// GenerateJWToken mocks base method.
func (m *MockJWTokenManager) GenerateJWToken(arg0 jwttoken.JWTokenData) (jwttoken.JWTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWToken", arg0)
	ret0, _ := ret[0].(jwttoken.JWTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWToken indicates an expected call of GenerateJWToken.
func (mr *MockJWTokenManagerMockRecorder) GenerateJWToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWToken", reflect.TypeOf((*MockJWTokenManager)(nil).GenerateJWToken), arg0)
}

// GeneratePasswordResetToken mocks base method.
func (m *MockJWTokenManager) GeneratePasswordResetToken(arg0 jwttoken.JWTokenData) (jwttoken.JWTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePasswordResetToken", arg0)
	ret0, _ := ret[0].(jwttoken.JWTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePasswordResetToken indicates an expected call of GeneratePasswordResetToken.
func (mr *MockJWTokenManagerMockRecorder) GeneratePasswordResetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePasswordResetToken", reflect.TypeOf((*MockJWTokenManager)(nil).GeneratePasswordResetToken), arg0)
}

// ParseJWToken mocks base method.
func (m *MockJWTokenManager) ParseJWToken(arg0 string) (jwttoken.JWTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseJWToken", arg0)
	ret0, _ := ret[0].(jwttoken.JWTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseJWToken indicates an expected call of ParseJWToken.
func (mr *MockJWTokenManagerMockRecorder) ParseJWToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseJWToken", reflect.TypeOf((*MockJWTokenManager)(nil).ParseJWToken), arg0)
}

// ParsePasswordResetToken mocks base method.
func (m *MockJWTokenManager) ParsePasswordResetToken(arg0 string) (jwttoken.JWTokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParsePasswordResetToken", arg0)
	ret0, _ := ret[0].(jwttoken.JWTokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParsePasswordResetToken indicates an expected call of ParsePasswordResetToken.
func (mr *MockJWTokenManagerMockRecorder) ParsePasswordResetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParsePasswordResetToken", reflect.TypeOf((*MockJWTokenManager)(nil).ParsePasswordResetToken), arg0)
}
