// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package config

import (
	"errors"
	"fmt"
)

const (
	// EnvTypeProduction is a EnvType of type production.
	EnvTypeProduction EnvType = "production"
	// EnvTypeDevelopment is a EnvType of type development.
	EnvTypeDevelopment EnvType = "development"
)

var ErrInvalidEnvType = errors.New("not a valid EnvType")

// String implements the Stringer interface.
func (x EnvType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EnvType) IsValid() bool {
	_, err := ParseEnvType(string(x))
	return err == nil
}

var _EnvTypeValue = map[string]EnvType{
	"production":  EnvTypeProduction,
	"development": EnvTypeDevelopment,
}

// ParseEnvType attempts to convert a string to a EnvType.
func ParseEnvType(name string) (EnvType, error) {
	if x, ok := _EnvTypeValue[name]; ok {
		return x, nil
	}
	return EnvType(""), fmt.Errorf("%s is %w", name, ErrInvalidEnvType)
}

const (
	// LogModeProd is a LogMode of type prod.
	LogModeProd LogMode = "prod"
	// LogModeDev is a LogMode of type dev.
	LogModeDev LogMode = "dev"
)

var ErrInvalidLogMode = errors.New("not a valid LogMode")

// String implements the Stringer interface.
func (x LogMode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LogMode) IsValid() bool {
	_, err := ParseLogMode(string(x))
	return err == nil
}

var _LogModeValue = map[string]LogMode{
	"prod": LogModeProd,
	"dev":  LogModeDev,
}

// ParseLogMode attempts to convert a string to a LogMode.
func ParseLogMode(name string) (LogMode, error) {
	if x, ok := _LogModeValue[name]; ok {
		return x, nil
	}
	return LogMode(""), fmt.Errorf("%s is %w", name, ErrInvalidLogMode)
}
