CREATE TABLE
    user_passwords (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
        user_password VARCHAR NOT NULL,
        user_id UUID NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        deleted_at TIMESTAMP WITH TIME ZONE
    );
